name: Build

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string

env:
  ALLOWED_REPOS: '["NexusMutual/frontend-react", "NexusMutual/frontend-next", "NexusMutual/cover-router", "NexusMutual/dummy-app"]'
  ALLOWED_BRANCHES: '["dev", "master"]'
  TARGET_BRANCH: ${{ inputs.branch || 'none' }}
  TARGET_REPO: ${{ inputs.repo || 'none' }}

jobs:

  check-calling-repo:
    runs-on: ubuntu-22.04
    environment: production
    timeout-minutes: 5
    steps:
      - name: print inputs
        run: echo inputs '${{ toJSON(inputs) }}'
      - name: print-gh
        run: echo gh '${{ toJSON(github) }}'
      - name: print-env
        run: echo env '${{ toJSON(env) }}'
      - name: print-vars
        run: echo vars '${{ toJSON(vars) }}'
      - name: print-secrets
        run: echo secrets '${{ toJSON(secrets) }}'
      - name: check repos
        if: ${{ ! contains(fromJSON(env.ALLOWED_REPOS), inputs.repo) }}
        run: exit 2 # making it fail if the repo is not allowed
      - name: check branch
        if: ${{ ! contains(fromJSON(env.ALLOWED_BRANCHES), inputs.branch) }}
        run: exit 1 # making it fail if the branch is not allowed
