name: Build

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      image:
        type: string
        required: true
      dockerfile:
        type: string
        default: Dockerfile
    secrets:
      TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    outputs:
      image-tag:
        value: ${{ jobs.build.outputs.image-tag }}

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    outputs:
      image-tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          ref: ${{ inputs.ref }}

      - name: Get version and revision
        id: vars
        run: |
          VERSION=$(jq -r .version package.json)
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "TAG=${VERSION}-${SHA_SHORT}" >> $GITHUB_OUTPUT
          echo 'IMAGE=${{ inputs.image }}' | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Build image
        env:
          IMAGE: ${{ steps.vars.outputs.IMAGE }}
          TAG: ${{ steps.vars.outputs.TAG }}
        run: docker build -t "ghcr.io/${IMAGE}:${TAG}" -f ${{ inputs.dockerfile }} .

      - name: Push image
        env:
          IMAGE: ${{ steps.vars.outputs.IMAGE }}
          TAG: ${{ steps.vars.outputs.TAG }}
        run: |
          echo "logging in"
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "pushing"
          docker push "ghcr.io/${IMAGE}:${TAG}"

      - name: Print tag
        run: echo "Pushed ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}"
