name: Bump version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      bump-and-commit-command:
        type: string
        default: npx semantic-release --dry-run --no-ci
      node-version:
        type: string
        default: 20
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true
      # GITHUB_TOKEN:
      #   required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Fingerprint PK
        run: |
          echo "${{ secrets.DEPLOYER_APP_PK }}" | wc -l
          echo "${{ secrets.DEPLOYER_APP_PK }}" | sha256sum

      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}

      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          repository: NexusMutual/workflows
          token: ${{ steps.app-token.outputs.token }}
          path: workflows-repo

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Set GITHUB_REF to inputs.ref
        run: echo "GITHUB_REF=refs/heads/${{ inputs.ref }}" >> $GITHUB_ENV

      - name: Bump and commit version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_REF
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          ${{ inputs.bump-and-commit-command }}

      - name: Push version
        run: git push origin ${{ inputs.ref }}

      - name: Tag
        if: inputs.ref == 'master'
        run: |
          git tag v${{ env.VERSION }}
          git push origin --tags
