name: Bump version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      bump-command:
        type: string
      node-version:
        type: string
        default: 20
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Fingerprint PK
        run: |
          echo "${{ secrets.DEPLOYER_APP_PK }}" | wc -l
          echo "${{ secrets.DEPLOYER_APP_PK }}" | sha256sum

      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}
          #repositories: ${{ inputs.repository }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}
#          repository: ${{ inputs.repository }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Get package.json version
        run: echo VERSION=$(node -p 'require("./package.json").version') >> $GITHUB_ENV

      - name: Commit and push
        run: |
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git add .
          git commit -m "chore: release v${{ env.VERSION }} [skip ci]"
          git push origin ${{ inputs.ref }}

      - name: Tag
        if: inputs.ref == 'master'
        run: |
          git tag v${{ env.VERSION }}
          git push origin --tags
