name: Bump version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      bump-command:
        type: string
        default: "echo Meep meep no bump command && exit 1"
      node-version:
        type: string
        default: '22'
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true
    outputs:
      bumped_version:
        description: "The version after bumping"
        value: ${{ jobs.bump.outputs.bumped_version }}

jobs:
  bump:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    outputs:
      bumped_version: ${{ steps.get-version.outputs.bumped_version }}
    steps:
      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Get bumped version
        id: get-version
        run: echo "bumped_version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"

          # check if there are changes to commit
          if [[ -z "$(git status --porcelain package.json package-lock.json **/package.json **/package-lock.json)" ]]; then
            echo "No changes to commit. Failing bump job."
            exit 1
          fi

          git add package.json package-lock.json $(git ls-files "**/package.json" "**/package-lock.json")
          git commit -m "chore(release): v${{ steps.get-version.outputs.bumped_version }} [skip ci]"
          git push origin ${{ inputs.ref }}
