name: Bump version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      bump-command:
        type: string
        default: "BUMP=$(timeout 5s npx conventional-recommended-bump --config .github/config/conventional-bump-setup.js --verbose | head -n1) || true; if [ ! -z \"$BUMP\" ]; then npm version \"$BUMP\" --no-git-tag-version; else echo \"No version bump\"; fi"
      node-version:
        type: string
        default: 20
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Fingerprint PK
        run: |
          echo "${{ secrets.DEPLOYER_APP_PK }}" | wc -l
          echo "${{ secrets.DEPLOYER_APP_PK }}" | sha256sum

      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Commit and push
        run: |
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"

          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain package.json package-lock.json)" ]]; then
            git add package.json package-lock.json
            git commit -m "chore(release): v$(jq -r .version package.json) [skip ci]"
            git push origin ${{ inputs.ref }}
          else
            echo "No changes to commit. Skipping commit and push."
          fi
