name: Bump version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        required: true
      bump-command:
        type: string
        default: npx semantic-release --dry-run --no-ci
      node-version:
        type: string
        default: 20
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true
      # GITHUB_TOKEN:
      #   required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Fingerprint PK
        run: |
          echo "${{ secrets.DEPLOYER_APP_PK }}" | wc -l
          echo "${{ secrets.DEPLOYER_APP_PK }}" | sha256sum

      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}

      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          repository: NexusMutual/workflows
          token: ${{ steps.app-token.outputs.token }}
          path: workflows-repo

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Commit and push
        run: |
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git add package.json package-lock.json
          git commit -m "chore(release): v$(node -p 'require("./package.json").version') [skip ci]"
          git push origin ${{ inputs.ref }}
