name: Fast forward branch

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      source-ref:
        type: string
        required: true
      target-ref:
        type: string
        required: true
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true

jobs:
  fast-forward:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}
          #repositories: ${{ inputs.repository }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.source-ref }}  # Always check out the source branch first

      - name: Fast-forward merge
        run: |
          git fetch origin
          
          # Check if target branch exists and store result
          if git show-ref --verify refs/remotes/origin/${{ inputs.target-ref }} > /dev/null 2>&1; then
            git checkout ${{ inputs.target-ref }}
            git merge origin/${{ inputs.source-ref }} --ff-only
          else
            echo "Target branch ${{ inputs.target-ref }} does not exist, creating it from ${{ inputs.source-ref }}"
            git checkout -b ${{ inputs.target-ref }} origin/${{ inputs.source-ref }}
          fi
          
          git push origin ${{ inputs.target-ref }}

      - name: Tag
        if: inputs.target-ref == 'master'
        run: |
          git tag v$(node -p 'require("./package.json").version')
          git push origin --tags
