name: Fast forward or rebase branch

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      source-ref:
        type: string
        required: true
      target-ref:
        type: string
        required: true
    secrets:
      DEPLOYER_APP_ID:
        required: true
      DEPLOYER_APP_PK:
        required: true

jobs:
  rebase:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.target-ref }}
          fetch-depth: 0

      - name: Rebase and push
        run: |
          echo "Rebasing ${{ inputs.target-ref }} branch onto ${{ inputs.source-ref }} branch"
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Deployooor"
          git rebase origin/${{ inputs.source-ref }} --rebase-merges
          git push origin ${{ inputs.target-ref }} --force
          echo "✅ Rebase and push successful"
